# Generated by Django 6.0.2 on 2026-02-12 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'demo_department',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'demo_tag',
            },
        ),
        migrations.CreateModel(
            name='WideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=200)),
                ('text_field', models.TextField(default='')),
                ('slug_field', models.SlugField(default='', max_length=100)),
                ('email_field', models.EmailField(default='', max_length=254)),
                ('url_field', models.URLField(default='')),
                ('ip_field', models.GenericIPAddressField(blank=True, null=True)),
                ('int_field', models.IntegerField(default=0)),
                ('bigint_field', models.BigIntegerField(default=0)),
                ('smallint_field', models.SmallIntegerField(default=0)),
                ('pos_int_field', models.PositiveIntegerField(default=0)),
                ('float_field', models.FloatField(default=0.0)),
                ('decimal_field', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('bool_field', models.BooleanField(default=False)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('datetime_field', models.DateTimeField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('duration_field', models.DurationField(blank=True, null=True)),
                ('uuid_field', models.UUIDField(default=uuid.uuid4)),
                ('json_field', models.JSONField(default=dict)),
                ('binary_field', models.BinaryField(blank=True, null=True)),
                ('file_field', models.FileField(blank=True, default='', upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_wide_model',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('focus_area', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='demo.department')),
            ],
            options={
                'db_table': 'demo_team',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_manager', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='demo.team')),
            ],
            options={
                'db_table': 'demo_employee',
            },
        ),
    ]
